### ISSUE TITLE
Rotas dos Componentes 

### ISSUE THREAD

**Issue by davirany** [mdsreq-fga-unb/2023.1-FamilyMusicSystem#12]
As rotas dos componentes a seguir se encontra no singular:
1. Alunos
2. Professores
3. Salas
Estes componentes devem renderizar listas de outros componentes, postanto as rotas deveriam estar no plural, por exemplo:
<b>localhost:4200/main/students</b>
ao invés de
<b>localhost:4200/main/student</b>

**Comment by maykonjuso** [comment]
As rotas foram atualizadas!
